unique_ids:
  assets:
    standard-page.html: 7XZOV2DAFAULNXUZKOMFNLQHPAOMHAXU
    theme.css: WOZ2YEBSCYPSICUM5EHUU67HARVYZH6U
  forms:
    Form1: LQDB6ZKNVBCYBTJH3OEPKTPEPUCP3RAX
  modules: {}
  scripts: {}
  server_modules: {}
